DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.8
  min_vel_x: -0.4

  max_vel_y: 0.4
  min_vel_y: -0.4

# The velocity when robot is moving in a straight line
  max_trans_vel:  0.8
  min_trans_vel:  0.11

  max_rot_vel: 2.75
  min_rot_vel: 1.37

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 15.0
  occdist_scale: 0.04
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true

EBandPlannerROS:
   xy_goal_tolerance: 0.03
   yaw_goal_tolerance: 0.05

   max_vel_lin: 0.3
   max_vel_th: 0.6

   max_acceleration: 0.2
   max_translational_acceleration: 0.2
   max_rotational_acceleration: 0.4

   differential_drive: false

   # rot_stopped_vel: 0.01
   # trans_stopped_vel: 0.01
   # marker_lifetime: 0.5
   # eband_min_relative_overlap: 0.7
   # eband_tiny_bubble_distance: 0.01
   # eband_tiny_bubble_expansion: 0.01
   # eband_internal_force_gain: 1.0
   # eband_external_force_gain: 2.0
   # num_iterations_eband_optimization: 3
   # eband_equilibrium_approx_max_recursion_depth: 4
   # eband_equilibrium_relative_overshoot: 0.75
   # eband_significant_force_lower_bound: 0.15
   # costmap_weight: 10.0
   # min_vel_lin: 0.1
   # min_vel_th: 0.0
   # min_in_place_vel_th: 0.2
   # in_place_trans_vel: 0.0
   # k_prop: 4.0
   # k_damp: 3.5
   # Ctrl_Rate: 10.0
   # virtual_mass: 0.75
   # rotation_correction_threshold: 0.5
   # bubble_velocity_multiplier: 2.0
   # rotation_threshold_multiplier: 1.0
   # disallow_hysteresis: false
