# base_local_planner: "dwa_local_planner/DWAPlannerROS"
# base_local_planner: "base_local_planner/TrajectoryPlannerROS"

base_local_planner: "eband_local_planner/EBandPlannerROS"
# base_local_planner: "teb_local_planner/TebLocalPlannerROS"

base_global_planner: "navfn/NavfnROS"
# base_global_planner: "global_planner/GlobalPlanner"
