global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true

  plugins:
   - {name: static_layer,            type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
  static_layer:
   lethal_cost_threshold: 60
  inflation_layer:
   cost_scaling_factor: 4.0
   inflation_radius: 0.9
